version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: tasktracker-db
    restart: always
    environment:
      POSTGRES_DB: tasktracker
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: tasktracker-backend
    depends_on:
      - postgres
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/tasktracker
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres

  frontend:
    build: ./frontend
    container_name: tasktracker-frontend
    depends_on:
      - backend
    ports:
      - "5174:5173"

volumes:
  postgres_data: